PACKAGE_NAME="gpd-i915"
PACKAGE_VERSION="1.0"
PRE_BUILD="prepare-source.sh ${kernelver}"
# kvmgt (GVT-g host module) is not needed and skipped to save build time on the Atom
MAKE[0]="make -j4 -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/src/drivers/gpu/drm/i915 KCFLAGS=-I${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build/src/inc/a CONFIG_DRM_I915_GVT_KVMGT= modules"
BUILT_MODULE_NAME[0]="i915"
BUILT_MODULE_LOCATION[0]="src/drivers/gpu/drm/i915"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
