title   Arch Linux
linux   /vmlinuz-linux
initrd  /initramfs-linux.img
options root=UUID=7a64638b-a129-47b5-a777-d0cd63d86cf1 rw fbcon=rotate:1 mitigations=off quiet loglevel=3 rd.udev.log_level=3 vt.global_cursor_default=0 gpiolib_acpi.ignore_wake=INT33FF:00@35
