#!/usr/bin/env python3
"""Fetch box art from thumbnails.libretro.com for ROMs in ~/Games/<system>/.

Matches on the bare title (tags in () and [] ignored), prefers USA releases,
and saves to <system>/media/<rom basename>/boxFront.png, where Pegasus finds it.
Also writes clean titles into a generated block at the end of metadata.pegasus.txt.
"""
import html, re, sys, urllib.parse, urllib.request
from pathlib import Path

GAMES = Path.home() / "Games"
SYSTEMS = {
    "nes": "Nintendo - Nintendo Entertainment System",
    "snes": "Nintendo - Super Nintendo Entertainment System",
    "gb": "Nintendo - Game Boy",
    "gbc": "Nintendo - Game Boy Color",
    "gba": "Nintendo - Game Boy Advance",
    "megadrive": "Sega - Mega Drive - Genesis",
    "mastersystem": "Sega - Master System - Mark III",
    "gamegear": "Sega - Game Gear",
    "segacd": "Sega - Mega-CD - Sega CD",
    "sega32x": "Sega - 32X",
    "pcengine": "NEC - PC Engine - TurboGrafx 16",
    "psx": "Sony - PlayStation",
}
BASE = "https://thumbnails.libretro.com"
REGION_PREF = ["(USA)", "(USA, Europe)", "(World)", "(Europe)", "(Japan, USA)", "(Japan)"]
SKIP_EXT = {".txt", ".png", ".jpg", ".cfg", ".srm", ".state"}


def norm(title):
    title = re.sub(r"[\(\[].*", "", title)          # drop tags
    title = re.sub(r",\s*the\b", "", title, flags=re.I)
    title = re.sub(r"^the\s+", "", title, flags=re.I)
    return re.sub(r"[^a-z0-9]", "", title.lower())


def listing(system):
    url = f"{BASE}/{urllib.parse.quote(system)}/Named_Boxarts/"
    with urllib.request.urlopen(url, timeout=30) as r:
        page = r.read().decode("utf-8", "replace")
    names = [html.unescape(urllib.parse.unquote(h)) for h in re.findall(r'href="([^"]+\.png)"', page)]
    index = {}
    for name in names:
        index.setdefault(norm(name), []).append(name)
    return index


def rank(name):
    for i, region in enumerate(REGION_PREF):
        if region in name:
            return (i, "(Rev" in name, len(name))
    return (len(REGION_PREF), "(Rev" in name, len(name))


MARK = "# --- generated by fetch-boxart.py, edits below are overwritten ---"


def clean(name):
    return re.sub(r"\s*[\(\[].*", "", Path(name).stem).strip()


def write_titles(d, titles):
    meta = d / "metadata.pegasus.txt"
    head = meta.read_text().split(MARK)[0].rstrip() + "\n"
    block = [MARK]
    for rom, title in titles:
        block += ["", f"game: {title}", f"file: {rom.name}"]
    meta.write_text(head + "\n" + "\n".join(block) + "\n")


def main():
    for folder, system in SYSTEMS.items():
        d = GAMES / folder
        roms = [p for p in sorted(d.glob("*")) if p.is_file() and p.suffix.lower() not in SKIP_EXT
                and p.name != "metadata.pegasus.txt"] if d.is_dir() else []
        if not roms:
            continue
        print(f"== {folder}")
        index = listing(system)
        titles = []
        for rom in roms:
            hits = index.get(norm(rom.stem))
            titles.append((rom, clean(min(hits, key=rank)) if hits else clean(rom.name)))
            dest = d / "media" / rom.stem / "boxFront.png"
            if dest.exists():
                print(f"   have   {rom.stem}")
                continue
            if not hits:
                print(f"   MISS   {rom.stem}")
                continue
            best = min(hits, key=rank)
            url = f"{BASE}/{urllib.parse.quote(system)}/Named_Boxarts/{urllib.parse.quote(best)}"
            dest.parent.mkdir(parents=True, exist_ok=True)
            urllib.request.urlretrieve(url, dest)
            print(f"   got    {rom.stem}  <-  {best}")
        if (d / "metadata.pegasus.txt").exists():
            write_titles(d, titles)


if __name__ == "__main__":
    sys.exit(main())
